import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "text-muted": "#8a8a8a",
        tertiary: "#f5f5f5",
        "error-container": "#3a3a3a",
        "border-active-cyan": "rgba(190, 190, 190, 0.45)",
        background: "#111111",
        "on-error-container": "#e5e5e5",
        "on-primary-container": "#111111",
        surface: "#111111",
        "on-primary-fixed-variant": "#555555",
        "border-glass": "rgba(255, 255, 255, 0.12)",
        "surface-container-highest": "#3a3a3a",
        secondary: "#d0d0d0",
        "inverse-surface": "#f5f5f5",
        "surface-bright": "#4a4a4a",
        "secondary-fixed": "#e5e5e5",
        "inverse-on-surface": "#2a2a2a",
        "surface-tint": "#bdbdbd",
        error: "#cfcfcf",
        "on-secondary-fixed-variant": "#4c4c4c",
        outline: "#999999",
        "surface-glass": "rgba(24, 24, 24, 0.84)",
        "on-tertiary-fixed": "#111111",
        "on-surface-variant": "#bdbdbd",
        "secondary-fixed-dim": "#cccccc",
        "signal-warning": "#bdbdbd",
        "tertiary-fixed-dim": "#b3b3b3",
        primary: "#f5f5f5",
        "on-background": "#ededed",
        "on-surface": "#ededed",
        "on-tertiary-fixed-variant": "#555555",
        "primary-fixed-dim": "#a6a6a6",
        "on-tertiary": "#222222",
        "on-error": "#202020",
        "on-primary-fixed": "#1a1a1a",
        "surface-variant": "#3a3a3a",
        "on-secondary-container": "#e0e0e0",
        "on-secondary": "#202020",
        "signal-danger": "#b0b0b0",
        "on-primary": "#1a1a1a",
        "primary-fixed": "#d1d1d1",
        "text-secondary": "#b5b5b5",
        "tertiary-fixed": "#e0e0e0",
        "surface-container-lowest": "#0b0b0b",
        "surface-container": "#1d1d1d",
        "signal-success": "#a8a8a8",
        "outline-variant": "#666666",
        "text-primary": "#f5f5f5",
        "primary-container": "#bdbdbd",
        "secondary-container": "#606060",
        "accent-violet-bright": "#a6a6a6",
        "on-tertiary-container": "#5c5c5c",
        "canvas-base": "#111111",
        "surface-container-high": "#2c2c2c",
        "surface-card": "#202020",
        "border-active-violet": "rgba(180, 180, 180, 0.45)",
        "surface-dim": "#111111",
        "tertiary-container": "#c7c7c7",
        "on-secondary-fixed": "#222222",
        "inverse-primary": "#5f5f5f",
        "surface-container-low": "#181818",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "space-xl": "2rem",
        "margin-desktop": "3rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.5rem",
        "margin-tablet": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "margin-mobile": "1rem",
        "max-width-content": "1280px",
      },
      fontFamily: {
        "code-xs": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "code-xs": [
          "10px",
          { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-lg": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-md": [
          "13px",
          { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "headline-sm": [
          "18px",
          {
            lineHeight: "26px",
            letterSpacing: "-0.005em",
            fontWeight: "600",
          },
        ],
        "body-sm": [
          "12px",
          { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "display-xl-mobile": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "code-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "display-xl": [
          "56px",
          { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" },
        ],
        "headline-lg-mobile": [
          "26px",
          {
            lineHeight: "34px",
            letterSpacing: "-0.015em",
            fontWeight: "700",
          },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
