import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "text-muted": "#64748B",
        tertiary: "#ecfaff",
        "error-container": "#93000a",
        "border-active-cyan": "rgba(0, 242, 254, 0.4)",
        background: "#0b1326",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#006a70",
        surface: "#0b1326",
        "on-primary-fixed-variant": "#004f53",
        "border-glass": "rgba(255, 255, 255, 0.08)",
        "surface-container-highest": "#2d3449",
        secondary: "#d0bcff",
        "inverse-surface": "#dae2fd",
        "surface-bright": "#31394d",
        "secondary-fixed": "#e9ddff",
        "inverse-on-surface": "#283044",
        "surface-tint": "#00dce6",
        error: "#ffb4ab",
        "on-secondary-fixed-variant": "#5516be",
        outline: "#849495",
        "surface-glass": "rgba(15, 23, 42, 0.72)",
        "on-tertiary-fixed": "#001f26",
        "on-surface-variant": "#b9cacb",
        "secondary-fixed-dim": "#d0bcff",
        "signal-warning": "#FBBF24",
        "tertiary-fixed-dim": "#4cd7f6",
        primary: "#e0fdff",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "on-tertiary-fixed-variant": "#004e5c",
        "primary-fixed-dim": "#00dce6",
        "on-tertiary": "#003640",
        "on-error": "#690005",
        "on-primary-fixed": "#002022",
        "surface-variant": "#2d3449",
        "on-secondary-container": "#c4abff",
        "on-secondary": "#3c0091",
        "signal-danger": "#EF4444",
        "on-primary": "#00373a",
        "primary-fixed": "#6ff6ff",
        "text-secondary": "#94A3B8",
        "tertiary-fixed": "#acedff",
        "surface-container-lowest": "#060e20",
        "surface-container": "#171f33",
        "signal-success": "#10B981",
        "outline-variant": "#3a494b",
        "text-primary": "#F8FAFC",
        "primary-container": "#00f2fe",
        "secondary-container": "#571bc1",
        "accent-violet-bright": "#A855F7",
        "on-tertiary-container": "#00697c",
        "canvas-base": "#090D16",
        "surface-container-high": "#222a3d",
        "surface-dim": "#0b1326",
        "tertiary-container": "#91e8ff",
        "on-secondary-fixed": "#23005c",
        "inverse-primary": "#00696f",
        "surface-container-low": "#131b2e",
        "surface-card": "#0F172A",
        "border-active-violet": "rgba(139, 92, 246, 0.4)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "space-xl": "2rem",
        "margin-desktop": "3rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.5rem",
        "margin-tablet": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "margin-mobile": "1rem",
        "max-width-content": "1280px",
      },
      fontFamily: {
        "code-xs": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "code-xs": [
          "10px",
          { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-lg": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-md": [
          "13px",
          { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "headline-sm": [
          "18px",
          {
            lineHeight: "26px",
            letterSpacing: "-0.005em",
            fontWeight: "600",
          },
        ],
        "body-sm": [
          "12px",
          { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "display-xl-mobile": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "code-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "display-xl": [
          "56px",
          { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" },
        ],
        "headline-lg-mobile": [
          "26px",
          {
            lineHeight: "34px",
            letterSpacing: "-0.015em",
            fontWeight: "700",
          },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
